before_script:
  - curl -O https://mirror.racket-lang.org/installers/6.9/racket-minimal-6.9-x86_64-linux.sh
  - chmod u+x racket-minimal-6.9-x86_64-linux.sh
  - ./racket-minimal-6.9-x86_64-linux.sh

stages:
  - build
  - test

cache:
  untracked: true

build:
  stage: build
  script:
    - ls
    - /usr/racket/bin/raco pkg install ./rex

test:
  stage: test
  script:
    - /usr/racket/bin/raco test -p rex
